---
# tasks file for my-role


- name: Install NTP service on ubuntu
  ansible.builtin.apt:
        name: ntp
        state: present
        update_cache: yes
  when: ansible_distribution == "Ubuntu"
    
- name: Start and enable NTP service on ubuntu 
  ansible.builtin.service:
        name: ntp
        state: started
        enabled: yes
  when: ansible_distribution == "Ubuntu"

- name: Copy chrony config file to ubuntu server
  ansible.builtin.template:
        src: ntpconf_ubuntu.j2
        dest: /etc/ntp.conf
        backup: yes
  when: ansible_distribution == "Ubuntu"
  notify: 
        - Restart NTP service on ubuntu
    

- name: Install NTP(Chrony) on CentOs
  ansible.builtin.yum:
        name: chrony
        state: present
  when: ansible_distribution == "CentOS"

- name: Start and enable NTP service on CentOs
  ansible.builtin.service:
        name: chronyd
        state: started
        enabled: yes
  when: ansible_distribution == "CentOS"

- name: Copy chrony config file to CentOs server
  ansible.builtin.template:
        src: ntpconf_centos.j2
        dest: /etc/chrony.conf
        backup: yes
  when: ansible_distribution == "CentOS"
  notify: 
        - Restart NTP service on CentOs
      