---
- name: Install and enable httpd server on webserver
  hosts: webserver
  become: yes
  tasks:
    - name: Install httpd server
      ansible.builtin.yum:
        name: httpd
        state: present
        update_cache: yes

    - name: Start and Enable the httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

    - name: Copy index.html file to remote server
      tags: webpage
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/html/index.html


