---

- name: Uninstall the NTP server
  hosts: all
  become: yes
  tasks:
    - name: Uninstall NTP service on ubuntu
      ansible.builtin.apt:
        name: ntp
        state: absent
      when: ansible_distribution == "Ubuntu"
  

    - name: Uninstall NTP(Chrony) on CentOs
      ansible.builtin.yum:
        name: chrony
        state: absent
      when: ansible_distribution == "CentOs"

     